# Generated by Django 4.2 on 2023-04-18 19:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='./default/noimage_user.jpg', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
